"""Mirrors constants in web_ui/screenshot-designer-server.ts."""

DESIGN_GRID = 16
SAFE_ZONE_TOP = 120
SAFE_ZONE_BOTTOM = 120
SAFE_ZONE_SIDES = 60
MIN_HEADLINE_SIZE = 60
MIN_CONTRAST = 4.5
MAX_ITERATIONS_PER_SCREENSHOT = 4
DEVICE_MIN_CANVAS_HEIGHT_RATIO = 0.55
DEVICE_MAX_CANVAS_HEIGHT_RATIO = 0.75
DEFAULT_PRESET_ID = "appstore_iphone_67"
